# Generated by Django 4.2.11 on 2025-04-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmoredVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('heavy_armored_vehicle', 'Тяжёлая бронетехника'), ('light_armored_vehicle', 'Лёгкая бронетехника')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('weapon_type', models.CharField(choices=[('large_caliber_gun', 'Крупнокалиберная пушка'), ('small_caliber_gun', 'Малокалиберная пушка'), ('large_caliber_machine_gun', 'Крупнокалиберный пулемёт'), ('small_caliber_machine_gun', 'Малокалиберный пулемёт')], max_length=50)),
                ('fuel', models.CharField(choices=[('diesel fuel', 'Солярка'), ('gazoline', 'Бензин')], max_length=50)),
                ('tower', models.CharField(choices=[('inhabited', 'Обитаемая'), ('uninhabited', 'Необитаемая')], max_length=50)),
                ('crew', models.IntegerField()),
                ('is_amphibian', models.BooleanField()),
                ('armor_thickness_cm', models.IntegerField()),
                ('nutrition_type', models.CharField(choices=[('machine', 'Автомат'), ('loader', 'Заряжающий')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('jet', 'Истребитель'), ('shtorm_aviation', 'Штурмовая авиация'), ('helicopter', 'Ветролёты')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('weapon_type', models.CharField(choices=[('gun', 'Скорострельная пушка'), ('rocket_air_earth', 'Воздух-земля'), ('rocket_air_air', 'Воздух-воздух')], max_length=50)),
                ('fuel', models.CharField(choices=[('kerosene', 'Керосин'), ('gazoline', 'Бензин')], max_length=50)),
                ('crew', models.IntegerField()),
            ],
        ),
    ]
