# Generated by Django 5.2 on 2025-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armoredvehicles',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ArmoredVehicles_photos/'),
        ),
        migrations.AddField(
            model_name='aviation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='aviation_photos/'),
        ),
    ]
